title: 冰兔的工具站
email: 3342894371@qq.com
description: >- 
  需要工具或者提建议，或者想做翻译苦力请加qq：3342894371
baseurl: "https://oas7poo.github.io/tools-site/"
url: ""
github_username:  Oas7pOo

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  blog:
    output: true
  tools:
    output: true
